apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: CHANGEME-hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: CHANGEME-hello-world
    spec:
      containers:
      - name: CHANGEME-hello-world-pod
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: CHANGEME-hello-world-service
spec:
  selector:
    app: CHANGEME-hello-world
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
